version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    healthcheck:
      test: mysql -u root -proot -e "show databases;"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql-data: